version: '3.5'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./docker/local/nginx/:/etc/nginx/conf.d/
            - ./:/var/www/
        ports:
            - "8001:80"
        depends_on:
            - app
        container_name: nginx

    app:
        build:
            context: .
            dockerfile: docker/local/app/Dockerfile
        volumes:
            - ./:/var/www/
        container_name: app
        depends_on:
            - db

    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: local
            MYSQL_USER: admin
            MYSQL_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - ./tmp/db:/var/lab/mysql
        container_name: db
